global:
  application_name: rt-client-facade
  default_ec2_keyname: flx-dev
  default_platform: 64bit Amazon Linux 2015.09 v2.0.8 running Tomcat 8 Java 8
  default_region: us-west-2
  profile: null
  sc: git
deploy:
  artifact: ./target/movie-api-0.0.1-SNAPSHOT.war
